### ISSUE TITLE
Maybe a little problem

### ISSUE THREAD

**Issue by xyy-Iv** [4uiiurz1/pytorch-deform-conv-v2#1]
I think the there is a mistake here:

` self.conv = nn.Conv2d(inc, outc, kernel_size=kernel_size, stride=kernel_size, bias=bias)`

`stride=kernel_size` shoule be `stride=stride`. Is that right?

**Comment by 4uiiurz1** [comment]
That is not a mistake.
Input of `self.conv` is `x_offset`, and `x_offset` is x in the paper.
Since offset can not be shared for each receptive field, x is arranged not overlapping for each receptive field (the size of x_offset is kernel_size*w * kernelsize*h).
Therefore, stride of `self.conv` needs to be the same as kernel_size.
